const productsData = [
  { name: "اخطبوط", category: "squid" },
  { name: "استاكوزا كندى", category: "other" },
  { name: "استاكوزا", category: "other" },
  { name: "انشوجا", category: "fish" },
  { name: "بطارخ", category: "other" },
  { name: "بلاك كود", category: "fish" },
  { name: "بلح بحر مفتوح", category: "other" },
  { name: "بلح بحر مقفول", category: "other" },
  { name: "تونه لوين", category: "fish" },
  { name: "تونه ساكو", category: "fish" },
  { name: "جمبرى ديل 20/16", category: "shrimp" },
  { name: "جمبرى ديل 25/21", category: "shrimp" },
  { name: "جمبرى ديل 30/26", category: "shrimp" },
  { name: "جمبرى ديل 40/30", category: "shrimp" },
  { name: "جمبرى قشر 15/13 - U15", category: "shrimp" },
  { name: "جمبرى قشر 8/12 - U10", category: "shrimp" },
  { name: "جمبرى قشر 20/16", category: "shrimp" },
  { name: "جمبرى قشر 25/21", category: "shrimp" },
  { name: "جمبرى قشر 30/20", category: "shrimp" },
  { name: "جمبرى قشر 40/30", category: "shrimp" },
  { name: "جمبرى قشر 50/40", category: "shrimp" },
  { name: "جمبرى قشر 60/50", category: "shrimp" },
  { name: "جمبرى لحم 110/90", category: "shrimp" },
  { name: "جمبرى لحم 15/11", category: "shrimp" },
  { name: "جمبرى لحم 15/13 - U15", category: "shrimp" },
  { name: "جمبرى لحم 20/16", category: "shrimp" },
  { name: "جمبرى لحم 25/21", category: "shrimp" },
  { name: "جمبرى لحم 30/26", category: "shrimp" },
  { name: "جمبرى لحم 35/31", category: "shrimp" },
  { name: "جمبرى لحم 40/30", category: "shrimp" },
  { name: "جمبرى لحم 50/40", category: "shrimp" },
  { name: "جمبرى لحم 60/50", category: "shrimp" },
  { name: "جمبرى لحم 70/60", category: "shrimp" },
  { name: "جمبرى لحم 90/70", category: "shrimp" },
  { name: "جمبرى لحم 200/100", category: "shrimp" },
  { name: "جمبرى قشر مكس صغير", category: "shrimp" },
  { name: "جمبرى قشر مكس كبير", category: "shrimp" },
  { name: "جندوفلى", category: "other" },
  { name: "ديول استاكوزا", category: "other" },
  { name: "ديول استاكوزا كندى", category: "other" },
  { name: "رنجه سايبه", category: "fish" },
  { name: "رنجه فاكيوم", category: "fish" },
  { name: "رنجه فيليه", category: "fish" },
  { name: "رؤوس كاليمارى", category: "squid" },
  { name: "سالمون بورشن", category: "fish" },
  { name: "سالمون دوبريه", category: "fish" },
  { name: "سالمون طولى بالجلد", category: "fish" },
  { name: "سالمون طولى بدون جلد", category: "fish" },
  { name: "سالمون فريش طيران", category: "fish" },
  { name: "سالمون فيليه", category: "fish" },
  { name: "سالمون هول", category: "fish" },
  { name: "سالمون هول فريش", category: "fish" },
  { name: "سبيط", category: "squid" },
  { name: "سبيط بالراس", category: "squid" },
  { name: "سبيط بدون راس", category: "squid" },
  { name: "سبيط دهور", category: "squid" },
  { name: "سردين", category: "fish" },
  { name: "سمك باسا خمسات", category: "fish" },
  { name: "سمك باسا كيلوهات", category: "fish" },
  { name: "سمك بربونى", category: "fish" },
  { name: "سمك بساريا", category: "fish" },
  { name: "سمك بلطى", category: "fish" },
  { name: "سمك بلطى فيليه", category: "fish" },
  { name: "سمك بورى", category: "fish" },
  { name: "سمك تونه", category: "fish" },
  { name: "سمك ثعابين", category: "fish" },
  { name: "سمك دنيس", category: "fish" },
  { name: "سمك سي باص", category: "fish" },
  { name: "سمك فيليه قشر بياض", category: "fish" },
  { name: "سمك قاروص", category: "fish" },
  { name: "سمك قاروص فيليه", category: "fish" },
  { name: "سمك لوط", category: "fish" },
  { name: "سمك لوط فيليه", category: "fish" },
  { name: "سمك مرجان", category: "fish" },
  { name: "سمك مكرونه", category: "fish" },
  { name: "سمك مكريل", category: "fish" },
  { name: "سمك مكريل فيليه", category: "fish" },
  { name: "سمك موسى", category: "fish" },
  { name: "سمك هامتشى", category: "fish" },
  { name: "سمك هامور", category: "fish" },
  { name: "سمك وقار", category: "fish" },
  { name: "سوفت شيل", category: "crab" },
  { name: "سى سكالوب", category: "other" },
  { name: "شوربه سى فود", category: "other" },
  { name: "صوابع كابوريا تايلاندى", category: "crab" },
  { name: "صوابع كابوريا صيني", category: "crab" },
  { name: "صوابع كابوريا هندى", category: "crab" },
  { name: "فسيخ", category: "other" },
  { name: "قشر جمبرى", category: "shrimp" },
  { name: "كابوريا دكر", category: "crab" },
  { name: "كابوريا نتى", category: "crab" },
  { name: "كاليمارى ابيض بلدي بالرأس", category: "squid" },
  { name: "كاليمارى ابيض بلدي صولو", category: "squid" },
  { name: "كاليمارى حمراء بلدي اقماع", category: "squid" },
  { name: "كاليمارى صينى", category: "squid" },
  { name: "كاليمارى حلقات", category: "squid" },
  { name: "كاليمارى فريش", category: "squid" },
  { name: "كفيار روسى", category: "other" },
  { name: "كينج كراب", category: "crab" },
  { name: "ملح بحر", category: "other" },
  { name: "ديوك رومى", category: "other" },
  { name: "ايس بوكس - صندوق فل", category: "other" },
  { name: "بطارخ", category: "other" },
  { name: "جمبرى بروكن", category: "shrimp" },
  { name: "جمبرى قشر 70/60", category: "shrimp" },
  { name: "بالتات بلاستيك", category: "other" },
  { name: "جمبري بيبى", category: "shrimp" },
  { name: "جمبري قشر U7", category: "shrimp" },
  { name: "جمبرى قشر U/8", category: "shrimp" },
  { name: "بيض كفيار", category: "other" },
  { name: "فراخ", category: "other" },
  { name: "كفيار", category: "other" },
  { name: "سبيط بدون راس وجناح", category: "squid" },
  { name: "شك صينى مكريل", category: "fish" },
  { name: "كاليمارى بالخارج", category: "squid" }
];
