const productsData = [
  { name: "اخطبوط", category: "squid", price: 220 },
  { name: "استاكوزا كندى", category: "other", price: 950 },
  { name: "استاكوزا", category: "other", price: 800 },
  { name: "انشوجا", category: "fish", price: 120 },
  { name: "بطارخ", category: "other", price: 450 },
  { name: "بلاك كود", category: "fish", price: 650 },
  { name: "بلح بحر مفتوح", category: "other", price: 150 },
  { name: "بلح بحر مقفول", category: "other", price: 130 },
  { name: "تونه لوين", category: "fish", price: 380 },
  { name: "تونه ساكو", category: "fish", price: 350 },
  { name: "جمبرى ديل 20/16", category: "shrimp", price: 320 },
  { name: "جمبرى ديل 25/21", category: "shrimp", price: 300 },
  { name: "جمبرى ديل 30/26", category: "shrimp", price: 280 },
  { name: "جمبرى ديل 40/30", category: "shrimp", price: 260 },
  { name: "جمبرى قشر 15/13 - U15", category: "shrimp", price: 420 },
  { name: "جمبرى قشر 8/12 - U10", category: "shrimp", price: 480 },
  { name: "جمبرى قشر 20/16", category: "shrimp", price: 380 },
  { name: "جمبرى قشر 25/21", category: "shrimp", price: 360 },
  { name: "جمبرى قشر 30/20", category: "shrimp", price: 340 },
  { name: "جمبرى قشر 40/30", category: "shrimp", price: 320 },
  { name: "جمبرى قشر 50/40", category: "shrimp", price: 280 },
  { name: "جمبرى قشر 60/50", category: "shrimp", price: 250 },
  { name: "جمبرى لحم 110/90", category: "shrimp", price: 180 },
  { name: "جمبرى لحم 15/11", category: "shrimp", price: 450 },
  { name: "جمبرى لحم 15/13 - U15", category: "shrimp", price: 430 },
  { name: "جمبرى لحم 20/16", category: "shrimp", price: 400 },
  { name: "جمبرى لحم 25/21", category: "shrimp", price: 380 },
  { name: "جمبرى لحم 30/26", category: "shrimp", price: 360 },
  { name: "جمبرى لحم 35/31", category: "shrimp", price: 340 },
  { name: "جمبرى لحم 40/30", category: "shrimp", price: 320 },
  { name: "جمبرى لحم 50/40", category: "shrimp", price: 290 },
  { name: "جمبرى لحم 60/50", category: "shrimp", price: 260 },
  { name: "جمبرى لحم 70/60", category: "shrimp", price: 230 },
  { name: "جمبرى لحم 90/70", category: "shrimp", price: 200 },
  { name: "جمبرى لحم 200/100", category: "shrimp", price: 170 },
  { name: "جمبرى قشر مكس صغير", category: "shrimp", price: 150 },
  { name: "جمبرى قشر مكس كبير", category: "shrimp", price: 250 },
  { name: "جندوفلى", category: "other", price: 90 },
  { name: "ديول استاكوزا", category: "other", price: 600 },
  { name: "ديول استاكوزا كندى", category: "other", price: 750 },
  { name: "رنجه سايبه", category: "fish", price: 80 },
  { name: "رنجه فاكيوم", category: "fish", price: 95 },
  { name: "رنجه فيليه", category: "fish", price: 140 },
  { name: "رؤوس كاليمارى", category: "squid", price: 70 },
  { name: "سالمون بورشن", category: "fish", price: 550 },
  { name: "سالمون دوبريه", category: "fish", price: 520 },
  { name: "سالمون طولى بالجلد", category: "fish", price: 480 },
  { name: "سالمون طولى بدون جلد", category: "fish", price: 500 },
  { name: "سالمون فريش طيران", category: "fish", price: 600 },
  { name: "سالمون فيليه", category: "fish", price: 580 },
  { name: "سالمون هول", category: "fish", price: 450 },
  { name: "سالمون هول فريش", category: "fish", price: 520 },
  { name: "سبيط", category: "squid", price: 190 },
  { name: "سبيط بالراس", category: "squid", price: 180 },
  { name: "سبيط بدون راس", category: "squid", price: 200 },
  { name: "سبيط دهور", category: "squid", price: 210 },
  { name: "سردين", category: "fish", price: 75 },
  { name: "سمك باسا خمسات", category: "fish", price: 110 },
  { name: "سمك باسا كيلوهات", category: "fish", price: 100 },
  { name: "سمك بربونى", category: "fish", price: 160 },
  { name: "سمك بساريا", category: "fish", price: 60 },
  { name: "سمك بلطى", category: "fish", price: 85 },
  { name: "سمك بلطى فيليه", category: "fish", price: 150 },
  { name: "سمك بورى", category: "fish", price: 110 },
  { name: "سمك تونه", category: "fish", price: 180 },
  { name: "سمك ثعابين", category: "fish", price: 250 },
  { name: "سمك دنيس", category: "fish", price: 190 },
  { name: "سمك سي باص", category: "fish", price: 220 },
  { name: "سمك فيليه قشر بياض", category: "fish", price: 180 },
  { name: "سمك قاروص", category: "fish", price: 210 },
  { name: "سمك قاروص فيليه", category: "fish", price: 280 },
  { name: "سمك لوط", category: "fish", price: 170 },
  { name: "سمك لوط فيليه", category: "fish", price: 240 },
  { name: "سمك مرجان", category: "fish", price: 130 },
  { name: "سمك مكرونه", category: "fish", price: 100 },
  { name: "سمك مكريل", category: "fish", price: 120 },
  { name: "سمك مكريل فيليه", category: "fish", price: 160 },
  { name: "سمك موسى", category: "fish", price: 180 },
  { name: "سمك هامتشى", category: "fish", price: 450 },
  { name: "سمك هامور", category: "fish", price: 350 },
  { name: "سمك وقار", category: "fish", price: 320 },
  { name: "سوفت شيل", category: "crab", price: 380 },
  { name: "سى سكالوب", category: "other", price: 420 },
  { name: "شوربه سى فود", category: "other", price: 180 },
  { name: "صوابع كابوريا تايلاندى", category: "crab", price: 150 },
  { name: "صوابع كابوريا صيني", category: "crab", price: 120 },
  { name: "صوابع كابوريا هندى", category: "crab", price: 130 },
  { name: "فسيخ", category: "other", price: 280 },
  { name: "قشر جمبرى", category: "shrimp", price: 50 },
  { name: "كابوريا دكر", category: "crab", price: 160 },
  { name: "كابوريا نتى", category: "crab", price: 180 },
  { name: "كاليمارى ابيض بلدي بالرأس", category: "squid", price: 200 },
  { name: "كاليمارى ابيض بلدي صولو", category: "squid", price: 220 },
  { name: "كاليمارى حمراء بلدي اقماع", category: "squid", price: 190 },
  { name: "كاليمارى صينى", category: "squid", price: 150 },
  { name: "كاليمارى حلقات", category: "squid", price: 170 },
  { name: "كاليمارى فريش", category: "squid", price: 210 },
  { name: "كفيار روسى", category: "other", price: 1500 },
  { name: "كينج كراب", category: "crab", price: 1200 },
  { name: "ملح بحر", category: "other", price: 20 },
  { name: "ديوك رومى", category: "other", price: 180 },
  { name: "ايس بوكس - صندوق فل", category: "other", price: 50 },
  { name: "بطارخ", category: "other", price: 450 },
  { name: "جمبرى بروكن", category: "shrimp", price: 160 },
  { name: "جمبرى قشر 70/60", category: "shrimp", price: 220 },
  { name: "بالتات بلاستيك", category: "other", price: 100 },
  { name: "جمبري بيبى", category: "shrimp", price: 120 },
  { name: "جمبري قشر U7", category: "shrimp", price: 500 },
  { name: "جمبرى قشر U/8", category: "shrimp", price: 490 },
  { name: "بيض كفيار", category: "other", price: 1200 },
  { name: "فراخ", category: "other", price: 110 },
  { name: "كفيار", category: "other", price: 1400 },
  { name: "سبيط بدون راس وجناح", category: "squid", price: 210 },
  { name: "شك صينى مكريل", category: "fish", price: 90 },
  { name: "كاليمارى بالخارج", category: "squid", price: 160 }
];
